// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTyunHVPWAxKdAPlIz67nOjXKz7S3yRt8',
    appId: '1:1092973278003:web:e434cf7ed0e9d33e888446',
    messagingSenderId: '1092973278003',
    projectId: 'absolutecinema-bb190',
    authDomain: 'absolutecinema-bb190.firebaseapp.com',
    storageBucket: 'absolutecinema-bb190.appspot.com',
    measurementId: 'G-CH641KDPNS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgMD4pYm-3c4sCEfoOF9JxF--aTEGBbtU',
    appId: '1:1092973278003:android:9b4813a8f6ec8056888446',
    messagingSenderId: '1092973278003',
    projectId: 'absolutecinema-bb190',
    storageBucket: 'absolutecinema-bb190.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFycdepqRtrEmWM-NUc6XKnIOyZDnwB1M',
    appId: '1:1092973278003:ios:353214c156d1fdd6888446',
    messagingSenderId: '1092973278003',
    projectId: 'absolutecinema-bb190',
    storageBucket: 'absolutecinema-bb190.appspot.com',
    iosBundleId: 'com.example.absoluteCinema',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFycdepqRtrEmWM-NUc6XKnIOyZDnwB1M',
    appId: '1:1092973278003:ios:353214c156d1fdd6888446',
    messagingSenderId: '1092973278003',
    projectId: 'absolutecinema-bb190',
    storageBucket: 'absolutecinema-bb190.appspot.com',
    iosBundleId: 'com.example.absoluteCinema',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTyunHVPWAxKdAPlIz67nOjXKz7S3yRt8',
    appId: '1:1092973278003:web:b28dd06581e02d0d888446',
    messagingSenderId: '1092973278003',
    projectId: 'absolutecinema-bb190',
    authDomain: 'absolutecinema-bb190.firebaseapp.com',
    storageBucket: 'absolutecinema-bb190.appspot.com',
    measurementId: 'G-FCB4GZ3RQC',
  );
}
